<?php

class AIAutoDeptTransferPlugin extends Plugin {
    var $config_class = 'AIAutoDeptTransferConfig';
    
    function bootstrap() {
        // Register signal handlers
        Signal::connect('ticket.created', array($this, 'onTicketCreated'));
        Signal::connect('object.view', array($this, 'onObjectView'));
        Signal::connect('ajax.scp', array($this, 'registerAjax'));
    }

    /**
     * @param array<string,mixed> $defaults
     *
     * @return AIAutoDeptTransferConfig
     */
    function getConfig(PluginInstance $instance = null, $defaults = [])
    {
        $config = null;
        if(null === $instance) {
            foreach ($this->getInstances() as $existingInstance) {
                if ($existingInstance->isEnabled()) {
                    $config = $existingInstance->getConfig();
                    break;
                }
            }
        }

        return $config ?? parent::getConfig($instance, $defaults); // TODO: Change the autogenerated stub
    }

    /**
     * Handle ticket.created signal for automatic processing
     *
     * @param \Ticket $ticket
     */
    function onTicketCreated($ticket) {
        $config = $this->getConfig();
        
        // Check if auto-transfer is enabled
        if (!$config->get('auto_transfer')) {
            if ($config->get('enable_logging')) {
                error_log("Auto Dept Transfer - Auto-transfer disabled, skipping ticket #" . $ticket->getNumber());
            }
            return;
        }
        
        try {
            if ($config->get('enable_logging')) {
                error_log("Auto Dept Transfer - Processing new ticket #" . $ticket->getNumber());
            }
            
            // Analyze ticket
            $analyzer = new AIAutoDeptTransferAnalyzer($config);
            $result = $analyzer->analyzeTicket($ticket->getId());
            
            if ($result['success']) {
                // Transfer ticket
                $transferred = $analyzer->transferTicket(
                    $ticket,
                    $result['dept_id'],
                    $result['reason']
                );
                
                if ($config->get('enable_logging')) {
                    if ($transferred) {
                        error_log("Auto Dept Transfer - Transferred ticket #" . $ticket->getNumber() . " to dept " . $result['dept_name']);
                    } else {
                        error_log("Auto Dept Transfer - Transfer not needed for ticket #" . $ticket->getNumber());
                    }
                }
            } elseif (isset($result['no_match'])) {
                // Log note that no match was found
                $analyzer->logTransferFailure($ticket, $result['message']);
                
                if ($config->get('enable_logging')) {
                    error_log("Auto Dept Transfer - No match found for ticket #" . $ticket->getNumber());
                }
            } else {
                // Log error
                if ($config->get('enable_logging')) {
                    error_log("Auto Dept Transfer - Error analyzing ticket #" . $ticket->getNumber() . ": " . ($result['error'] ?? 'Unknown error'));
                }
                
                $analyzer->logTransferFailure($ticket, $result['error'] ?? 'Analysis failed');
            }
            
        } catch (Exception $e) {
            if ($config->get('enable_logging')) {
                error_log("Auto Dept Transfer - Exception processing ticket: " . $e->getMessage());
            }
        }
    }
    
    /**
     * Register AJAX endpoints
     */
    function registerAjax($dispatcher, $data=null) {
        $dispatcher->append(
            url_post('^/ai-auto-dept-transfer/analyze', 'ai_auto_dept_transfer_handle_analyze')
        );
    }
    
    /**
     * Inject assets when viewing a ticket
     */
    function onObjectView($object, $type=null) {
        if ($object && is_a($object, 'Ticket')) {
            $this->loadAssets($object);
        }
    }
    
    /**
     * Load CSS and JavaScript assets for ticket view
     */
    function loadAssets($object) {
        global $thisstaff;
        
        $config = $this->getConfig();
        $path = dirname(__FILE__);

        // Get current staff member's department ID
        $staff_dept_id = 0;
        if ($thisstaff && method_exists($thisstaff, 'getDeptId')) {
            $staff_dept_id = $thisstaff->getDeptId();
        }

        $is_manual_button_allowed = false;
        // Get allowed departments (returns array of id => name or null/empty)
        $allowed_depts = $config->get('allowed_depts');
        if (is_null($allowed_depts)) {
            $is_manual_button_allowed = true;
        } elseif ($staff_dept_id) {
            $is_manual_button_allowed = in_array($staff_dept_id, $allowed_depts);
        }
        
        // Load CSS
        echo '<style type="text/css">';
        @readfile($path . '/css/ai-auto-dept-transfer.css');
        echo '</style>';
        
        // Pass config to JavaScript
        echo '<script type="text/javascript">
            var AI_AUTO_DEPT_TRANSFER_CONFIG = {
                ajax_url: "ajax.php/ai-auto-dept-transfer",
                ticket_id: ' . $object->getId() . ',
                is_manual_button_allowed: ' . json_encode($is_manual_button_allowed) . ',
                enable_logging: ' . ($config->get('enable_logging') ? 'true' : 'false') . '
            };
        </script>';
        
        // Load JavaScript
        echo '<script type="text/javascript">';
        @readfile($path . '/js/auto-dept-transfer.js');
        echo '</script>';
    }
}

